### ISSUE TITLE
In the simulator is running, the program crashes when selecting the camera

### ISSUE THREAD

**Issue by xf8** [xiekw2010/DXImagePicker#2]
DXPhotoSelectBrowser[1843:219933] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'attempt to scroll to invalid index path: <NSIndexPath: 0xc000000000a00016> {length = 2, path = 0 - 5}'

**Comment by xiekw2010** [comment]
Simulator does not support camera device, how about in a real device?
